font.normal = { family = "JetBrainsMono Nerd Font" }
font.size = 12
colors.primary.background = '#181616'
colors.primary.foreground = '#c5c9c5'
colors.normal.black =   '#0d0c0c'
colors.normal.red =     '#c4746e'
colors.normal.green =   '#8a9a7b'
colors.normal.yellow =  '#c4b28a'
colors.normal.blue =    '#8ba4b0'
colors.normal.magenta = '#a292a3'
colors.normal.cyan =    '#8ea4a2'
colors.normal.white =   '#C8C093'

colors.bright.black =   '#a6a69c'
colors.bright.red =     '#E46876'
colors.bright.green =   '#87a987'
colors.bright.yellow =  '#E6C384'
colors.bright.blue =    '#7FB4CA'
colors.bright.magenta = '#938AA9'
colors.bright.cyan =    '#7AA89F'
colors.bright.white =   '#c5c9c5'

colors.selection.background = '#2D4F67'
colors.selection.foreground = '#C8C093'

colors.indexed_colors = [{ index = 16, color = '#b6927b' }, { index = 17, color = '#b98d7b' }]
