import QtQuick

QtObject {
    readonly property color toolbar_background: "#11110F"
    readonly property color workspace_idle_background: "#44463F"
    readonly property color accent_green: "#87A987"
    readonly property color workspace_active_background: "#1D2A20"
    readonly property color workspace_hover_background: "#2A382E"
    readonly property color workspace_hover_border: "#6B8A6C"
    readonly property color text_dim: "#70746E"
    readonly property color text_muted: "#848780"
    readonly property color text_primary: "#C5C9C5"
    readonly property color accent_blue: "#8BA4B0"
    readonly property color text_selected: "#B7C7AD"
    readonly property color toolbar_accent: "#49634F"
    readonly property color prompt_separator: "#51534D"
    readonly property color accent_warm: "#B6927B"
    readonly property color accent_gold: "#C4B28A"
    readonly property color panel_background: "#151914"
    readonly property color accent_lime: "#A3BE8C"
    readonly property color date_30_1_0: "#536057"
    readonly property color lock_command_index: "#677169"
    readonly property color desktop_state_instruction: "#C4CEC1"
    readonly property color power_menu_terminal_prompt: "#557158"
    readonly property color current_notification_toast: "#729476"
    readonly property color music_label: "#AEB6AB"
    readonly property color accent_danger: "#C4746E"
    readonly property color canvas_background: "#0D0E0C"
    readonly property color day_31: "#29402E"
    readonly property color shutdown_command: "#302322"
    readonly property color terminal_menu_rule: "#3E5942"
    readonly property color states_subtitle: "#88948A"
    readonly property color terminal_concept_description: "#A6A69C"
}
